DISCORD_CLIENT_ID = "1471873085023060061"
DISCORD_CLIENT_SECRET = "4jhT7Ob7JfTqyXjKOal4G-5VkClrMZQh"
DISCORD_REDIRECT_URI = "https://vlcards.streamlit.app/"
DISCORD_STATE_SECRET = "vlcards_super_secret_random_string_847239847239"

